all:
	echo Making EECalABSum.
	(cd EECalABSum r && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_EECalABSum.
clean:
	(cd EECalABSum                 && make -is clean && cd ..)
	rm -f *~
